name: nodejs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install
        run: make dependency
      - name: Build
        run: make build
      - name: Setup
        run: make setup
      - name: Lint
        run: make lint
      - name: Test
        run: make test
