name: Node CI

on:
  - push
  - pull_request

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install
        run: make setup
      - name: Build
        run: npm run build
      - name: Lint
        run: make lint
      - name: Test
        run: make test
